services:
  gin:
    build: .
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: twitter_db
      APP_URL: http://localhost:8080
      SMTP_ADDRESS: mailcatcher:1025
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: twitter_db
    ports:
      - '5432:5432'
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d twitter_db']
      interval: 5s
      timeout: 5s
      retries: 5
