services:
  gin:
    build: .
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: twitter_db
      APP_URL: http://localhost:8080
      FRONT_APP_URL: http://localhost:3000

      ENV: prod
      GMAIL_USER:
      GMAIL_PASS:
      SMTP_ADDRESS: smtp.gmail.com:587

      # ENV: dev
      # SMTP_ADDRESS: mailcatcher:1025
      # MAIL_FROM: noreply@example.com

      REDIS_ADDRESS: redis_server:6379
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis_server:
        condition: service_healthy
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: twitter_db
    ports:
      - '5432:5432'
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d twitter_db']
      interval: 5s
      timeout: 5s
      retries: 5
  redis_server:
    image: redis:latest
    ports:
      - '16379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
