// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID               int32            `json:"id"`
	Email            string           `json:"email"`
	Password         string           `json:"password"`
	UserName         pgtype.Text      `json:"user_name"`
	PhoneNumber      pgtype.Text      `json:"phone_number"`
	NickName         pgtype.Text      `json:"nick_name"`
	SelfIntroduction pgtype.Text      `json:"self_introduction"`
	Place            pgtype.Text      `json:"place"`
	WebSite          pgtype.Text      `json:"web_site"`
	DateOfBirth      pgtype.Date      `json:"date_of_birth"`
	ProfileImage     pgtype.Text      `json:"profile_image"`
	AvatarImage      pgtype.Text      `json:"avatar_image"`
	IsActive         pgtype.Bool      `json:"is_active"`
	ActivationToken  pgtype.Text      `json:"activation_token"`
	ActivatedAt      pgtype.Timestamp `json:"activated_at"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}
