// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users
SET is_active = true, activation_token = NULL, activated_at = CURRENT_TIMESTAMP
WHERE activation_token = $1
`

func (q *Queries) ActivateUser(ctx context.Context, activationToken pgtype.Text) error {
	_, err := q.db.Exec(ctx, activateUser, activationToken)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  mail,
  password,
  is_active,
  activation_token
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, mail, password, user_name, phone_number, nick_name, self_introduction, place, web_site, date_of_birth, profile_image, avatar_image, is_active, activation_token, activated_at, created_at, updated_at
`

type CreateUserParams struct {
	Mail            string      `json:"mail"`
	Password        string      `json:"password"`
	IsActive        pgtype.Bool `json:"is_active"`
	ActivationToken pgtype.Text `json:"activation_token"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Mail,
		arg.Password,
		arg.IsActive,
		arg.ActivationToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Mail,
		&i.Password,
		&i.UserName,
		&i.PhoneNumber,
		&i.NickName,
		&i.SelfIntroduction,
		&i.Place,
		&i.WebSite,
		&i.DateOfBirth,
		&i.ProfileImage,
		&i.AvatarImage,
		&i.IsActive,
		&i.ActivationToken,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, mail, password, is_active
FROM users
WHERE mail = $1
`

type GetUserByEmailRow struct {
	ID       int32       `json:"id"`
	Mail     string      `json:"mail"`
	Password string      `json:"password"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, mail string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, mail)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Mail,
		&i.Password,
		&i.IsActive,
	)
	return i, err
}
