// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  mail,
  password
) VALUES (
  $1, $2
)
RETURNING id, mail, password, user_name, phone_number, nick_name, self_introduction, place, web_site, date_of_birth, profile_image, avatar_image, created_at, updated_at
`

type CreateUserParams struct {
	Mail     string `json:"mail"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Mail, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Mail,
		&i.Password,
		&i.UserName,
		&i.PhoneNumber,
		&i.NickName,
		&i.SelfIntroduction,
		&i.Place,
		&i.WebSite,
		&i.DateOfBirth,
		&i.ProfileImage,
		&i.AvatarImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
